name: React app deployment

on:
  push:
    branches: ["development"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: pwd
      - run: |
          cd /home/runner
          mkdir react-demo-app
          cp -r /home/runner/work/react-app-demo/react-app-demo/build/* /home/runner/react-demo-app/
          cd react-demo-app
          git config --global user.email "praveenkumar.s@cloudeq.com"
          git config --global user.name "praveen-kumar-ceq"
          git init
          git checkout -b azure-web-app
          git add .
          git commit -m "Build:`date +'%Y-%m-%d %H:%M:%S'`"
          git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/praveen-kumar-ceq/react-app-demo.git
          git pull --rebase
          git push -u origin azure-web-app
          echo All task done
